import { Staff } from "@/config/columns";

export const sidebarLinks = [
	{
		label: "Dashboard",
		route: "/dashboard",
		imgUrl: "/icons/dashboard.svg",
	},
	{
		label: "Staff Management",
		route: "/staff-management",
		imgUrl: "/icons/staff.svg",
	},
	{
		label: "Farmer Management",
		route: "/farmer-management",
		imgUrl: "/icons/farmer.svg",
	},
	{
		label: "Project Management",
		route: "/project-management",
		imgUrl: "/icons/project.svg",
	},
	{
		label: "Device Management",
		route: "/device-management",
		imgUrl: "/icons/device.svg",
	},
	{
		label: "Location Management",
		route: "/location-management",
		imgUrl: "/icons/location.svg",
	},
	{
		label: "Log Activity",
		route: "/log-activity",
		imgUrl: "/icons/log.svg",
	},
];

export const data: Staff[] = [
	{
		id: "728ed52f",
		name: "Confidence Clinton",
		staff: "STF001",
		email: "confidinho@yahoo.com",
		date: "12th Jan. 2025",
		status: "active",
		role: "admin",
	},
	{
		id: "728ed530",
		name: "Ayomide Kolawole",
		staff: "STF002",
		email: "ayomide@example.com",
		date: "15th Feb. 2025",
		status: "active",
		role: "accountant",
	},
	{
		id: "728ed531",
		name: "Promise Johnson",
		staff: "STF003",
		email: "promise@example.com",
		date: "20th Mar. 2025",
		status: "inactive",
		role: "developer",
	},
	{
		id: "728ed532",
		name: "Samson Daniel",
		staff: "STF004",
		email: "samson@example.com",
		date: "5th Apr. 2025",
		status: "active",
		role: "designer",
	},
	{
		id: "728ed533",
		name: "Victoria Ajayi",
		staff: "STF005",
		email: "victoria@example.com",
		date: "10th May 2025",
		status: "active",
		role: "manager",
	},
	{
		id: "728ed534",
		name: "Chinedu Emeka",
		staff: "STF006",
		email: "chinedu@example.com",
		date: "18th Jun. 2025",
		status: "active",
		role: "developer",
	},
	{
		id: "728ed535",
		name: "Esther Omolayo",
		staff: "STF007",
		email: "esther@example.com",
		date: "22nd Jul. 2025",
		status: "inactive",
		role: "marketing",
	},
	{
		id: "728ed536",
		name: "Abiola Martins",
		staff: "STF008",
		email: "abiola@example.com",
		date: "30th Aug. 2025",
		status: "active",
		role: "support",
	},
	{
		id: "728ed537",
		name: "Grace Ighodaro",
		staff: "STF009",
		email: "grace@example.com",
		date: "5th Sep. 2025",
		status: "active",
		role: "admin",
	},
	{
		id: "728ed538",
		name: "John Doe",
		staff: "STF010",
		email: "john@example.com",
		date: "12th Oct. 2025",
		status: "inactive",
		role: "developer",
	},
	{
		id: "728ed539",
		name: "Faith Oladimeji",
		staff: "STF011",
		email: "faith@example.com",
		date: "25th Nov. 2025",
		status: "active",
		role: "designer",
	},
	{
		id: "728ed540",
		name: "David Oluwadamilare",
		staff: "STF012",
		email: "david@example.com",
		date: "30th Dec. 2025",
		status: "inactive",
		role: "accountant",
	},
	{
		id: "728ed541",
		name: "Mary Okoro",
		staff: "STF013",
		email: "mary@example.com",
		date: "3rd Jan. 2026",
		status: "active",
		role: "manager",
	},
	{
		id: "728ed542",
		name: "Samuel Nwachukwu",
		staff: "STF014",
		email: "samuel@example.com",
		date: "15th Feb. 2026",
		status: "active",
		role: "support",
	},
	{
		id: "728ed543",
		name: "Joy Adaobi",
		staff: "STF015",
		email: "joy@example.com",
		date: "20th Mar. 2026",
		status: "inactive",
		role: "marketing",
	},
	{
		id: "728ed544",
		name: "Paul Arinze",
		staff: "STF016",
		email: "paul@example.com",
		date: "25th Apr. 2026",
		status: "active",
		role: "developer",
	},
	{
		id: "728ed545",
		name: "Ruth Bassey",
		staff: "STF017",
		email: "ruth@example.com",
		date: "5th May 2026",
		status: "active",
		role: "accountant",
	},
	{
		id: "728ed546",
		name: "Emmanuel Udo",
		staff: "STF018",
		email: "emmanuel@example.com",
		date: "12th Jun. 2026",
		status: "inactive",
		role: "admin",
	},
	{
		id: "728ed547",
		name: "Glory Okafor",
		staff: "STF019",
		email: "glory@example.com",
		date: "18th Jul. 2026",
		status: "active",
		role: "developer",
	},
	{
		id: "728ed548",
		name: "Michael Olagunju",
		staff: "STF020",
		email: "michael@example.com",
		date: "30th Aug. 2026",
		status: "active",
		role: "manager",
	},
];
