import { Staff } from "@/config/columns";
import { Device } from "@/config/device-columns";
import { Farmer } from "@/config/farmer-columns";
import { Group } from "@/config/group-columns";
import { Logs } from "@/config/log-columns";
import { Posting } from "@/config/posting-columns";
import { Project } from "@/config/project-columns";

export const sidebarLinks = [
	{
		label: "Dashboard",
		route: "/dashboard",
		imgUrl: "/icons/dashboard.svg",
	},
	{
		label: "Farmer Management",
		route: "/farmer-management",
		imgUrl: "/icons/farmer.svg",
	},
	{
		label: "Project Management",
		route: "/project-management",
		imgUrl: "/icons/project.svg",
	},
	{
		label: "Device Management",
		route: "/device-management",
		imgUrl: "/icons/device.svg",
	},

	{
		label: "Staff Management",
		route: "/staff-management",
		imgUrl: "/icons/staff.svg",
	},
	{
		label: "Location Management",
		route: "/location-management",
		imgUrl: "/icons/location.svg",
	},
	{
		label: "Log Activity",
		route: "/log-activity",
		imgUrl: "/icons/log.svg",
	},
];

export const staffData: Staff[] = [
	{
		id: "728ed52f",
		name: "Confidence Clinton",
		staff: "STF001",
		email: "confidinho@yahoo.com",
		date: "12th Jan. 2025",
		status: "active",
		role: "admin",
	},
	{
		id: "728ed530",
		name: "Ayomide Kolawole",
		staff: "STF002",
		email: "ayomide@example.com",
		date: "15th Feb. 2025",
		status: "active",
		role: "accountant",
	},
	{
		id: "728ed531",
		name: "Promise Johnson",
		staff: "STF003",
		email: "promise@example.com",
		date: "20th Mar. 2025",
		status: "inactive",
		role: "developer",
	},
	{
		id: "728ed532",
		name: "Samson Daniel",
		staff: "STF004",
		email: "samson@example.com",
		date: "5th Apr. 2025",
		status: "active",
		role: "designer",
	},
	{
		id: "728ed533",
		name: "Dolapo Ojelabi",
		staff: "STF005",
		email: "victoria@example.com",
		date: "10th May 2025",
		status: "active",
		role: "manager",
	},
	{
		id: "728ed534",
		name: "Chinedu Emeka",
		staff: "STF006",
		email: "chinedu@example.com",
		date: "18th Jun. 2025",
		status: "active",
		role: "developer",
	},
	{
		id: "728ed535",
		name: "Esther Omolayo",
		staff: "STF007",
		email: "esther@example.com",
		date: "22nd Jul. 2025",
		status: "inactive",
		role: "marketing",
	},
	{
		id: "728ed536",
		name: "Abiola Martins",
		staff: "STF008",
		email: "abiola@example.com",
		date: "30th Aug. 2025",
		status: "active",
		role: "support",
	},
	{
		id: "728ed537",
		name: "Grace Ighodaro",
		staff: "STF009",
		email: "grace@example.com",
		date: "5th Sep. 2025",
		status: "active",
		role: "admin",
	},
	{
		id: "728ed538",
		name: "John Doe",
		staff: "STF010",
		email: "john@example.com",
		date: "12th Oct. 2025",
		status: "inactive",
		role: "developer",
	},
	{
		id: "728ed539",
		name: "Faith Oladimeji",
		staff: "STF011",
		email: "faith@example.com",
		date: "25th Nov. 2025",
		status: "active",
		role: "designer",
	},
	{
		id: "728ed540",
		name: "David Oluwadamilare",
		staff: "STF012",
		email: "david@example.com",
		date: "30th Dec. 2025",
		status: "inactive",
		role: "accountant",
	},
	{
		id: "728ed541",
		name: "Mary Okoro",
		staff: "STF013",
		email: "mary@example.com",
		date: "3rd Jan. 2026",
		status: "active",
		role: "manager",
	},
	{
		id: "728ed542",
		name: "Samuel Nwachukwu",
		staff: "STF014",
		email: "samuel@example.com",
		date: "15th Feb. 2026",
		status: "active",
		role: "support",
	},
	{
		id: "728ed543",
		name: "Joy Adaobi",
		staff: "STF015",
		email: "joy@example.com",
		date: "20th Mar. 2026",
		status: "inactive",
		role: "marketing",
	},
	{
		id: "728ed544",
		name: "Paul Arinze",
		staff: "STF016",
		email: "paul@example.com",
		date: "25th Apr. 2026",
		status: "active",
		role: "developer",
	},
	{
		id: "728ed545",
		name: "Ruth Bassey",
		staff: "STF017",
		email: "ruth@example.com",
		date: "5th May 2026",
		status: "active",
		role: "accountant",
	},
	{
		id: "728ed546",
		name: "Emmanuel Udo",
		staff: "STF018",
		email: "emmanuel@example.com",
		date: "12th Jun. 2026",
		status: "inactive",
		role: "admin",
	},
	{
		id: "728ed547",
		name: "Glory Okafor",
		staff: "STF019",
		email: "glory@example.com",
		date: "18th Jul. 2026",
		status: "active",
		role: "developer",
	},
	{
		id: "728ed548",
		name: "Michael Olagunju",
		staff: "STF020",
		email: "michael@example.com",
		date: "30th Aug. 2026",
		status: "active",
		role: "manager",
	},
];

export const farmerData: Farmer[] = [
	{
		id: "00001",
		firstName: "Confidence",
		lastName: "Clinton",
		groupName: "Ayomide Group",
		siteName: "Atunrase",
		sector: "Gbagada",
		dateJoined: "2025-01-12",
		biometricStatus: "both",
	},
	{
		id: "00002",
		firstName: "Emeka",
		lastName: "Obi",
		groupName: "Green Harvest",
		siteName: "Ajah",
		sector: "Lekki",
		dateJoined: "2025-03-12",
		biometricStatus: "facial",
	},
	{
		id: "00003",
		firstName: "Aisha",
		lastName: "Bello",
		groupName: "Agro Leaders",
		siteName: "Ikeja",
		sector: "Mainland",
		dateJoined: "2025-02-12",
		biometricStatus: "fingerprint",
	},
	{
		id: "00004",
		firstName: "Tunde",
		lastName: "Adeyemi",
		groupName: "Farm Innovators",
		siteName: "Epe",
		sector: "Ikorodu",
		dateJoined: "2025-01-14",
		biometricStatus: "none",
	},
	{
		id: "00005",
		firstName: "Fatima",
		lastName: "Danladi",
		groupName: "Sustainable Crops",
		siteName: "Badagry",
		sector: "Ojo",
		dateJoined: "2025-01-18",
		biometricStatus: "both",
	},
	{
		id: "00006",
		firstName: "John",
		lastName: "Doe",
		groupName: "Green Earth",
		siteName: "Surulere",
		sector: "Lagos Island",
		dateJoined: "2025-04-12",
		biometricStatus: "facial",
	},
	{
		id: "00007",
		firstName: "Grace",
		lastName: "Okonkwo",
		groupName: "Harvest Kings",
		siteName: "Agege",
		sector: "Iyana Ipaja",
		dateJoined: "2024-11-12",
		biometricStatus: "fingerprint",
	},
	{
		id: "00008",
		firstName: "David",
		lastName: "Akpan",
		groupName: "AgroTech",
		siteName: "Ikotun",
		sector: "Alimosho",
		dateJoined: "2024-11-24",
		biometricStatus: "none",
	},
	{
		id: "00009",
		firstName: "Mary",
		lastName: "Johnson",
		groupName: "Organic Farmers",
		siteName: "Festac",
		sector: "Amuwo Odofin",
		dateJoined: "2024-12-12",
		biometricStatus: "both",
	},
	{
		id: "00010",
		firstName: "Samuel",
		lastName: "Eze",
		groupName: "Golden Fields",
		siteName: "Mushin",
		sector: "Oshodi",
		dateJoined: "2025-12-23",
		biometricStatus: "facial",
	},
];

export const projectData: Project[] = [
	{
		id: "00001",
		projectName: "Fertilizer Distribution",
		startDate: "12th Jan. 2025",
		endDate: "12th Jan. 2026",
		status: "ongoing",
	},
	{
		id: "00002",
		projectName: "Irrigation Expansion",
		startDate: "15th Feb. 2025",
		endDate: "20th Dec. 2025",
		status: "yet to start",
	},
	{
		id: "00003",
		projectName: "Soil Testing Initiative",
		startDate: "10th Mar. 2025",
		endDate: "10th Sep. 2025",
		status: "ongoing",
	},
	{
		id: "00004",
		projectName: "Crop Rotation Program",
		startDate: "1st Apr. 2025",
		endDate: "1st Apr. 2026",
		status: "close",
	},
	{
		id: "00005",
		projectName: "Organic Farming Training",
		startDate: "5th May. 2025",
		endDate: "5th Nov. 2025",
		status: "ongoing",
	},
	{
		id: "00006",
		projectName: "Smart Farming Implementation",
		startDate: "12th Jun. 2025",
		endDate: "12th Dec. 2025",
		status: "yet to start",
	},
	{
		id: "00007",
		projectName: "Livestock Breeding Program",
		startDate: "20th Jul. 2025",
		endDate: "20th Jan. 2026",
		status: "ongoing",
	},
	{
		id: "00008",
		projectName: "Pest Control Research",
		startDate: "1st Aug. 2025",
		endDate: "1st Feb. 2026",
		status: "yet to start",
	},
	{
		id: "00009",
		projectName: "Farmers' Cooperative Expansion",
		startDate: "10th Sep. 2025",
		endDate: "10th Mar. 2026",
		status: "close",
	},
	{
		id: "00010",
		projectName: "Climate Change Adaptation",
		startDate: "5th Oct. 2025",
		endDate: "5th Apr. 2026",
		status: "ongoing",
	},
];

export const logData: Logs[] = [
	{
		id: "00001",
		fullName: "Confidence Clinton",
		date: "25/12/2024 - 15:34:00",
		module: "Farmer",
		actions: "update",
		description: "Updated farmer details for record 00023.",
	},
	{
		id: "00002",
		fullName: "Ayomide Kolawole",
		date: "26/12/2024 - 10:15:23",
		module: "Location",
		actions: "create",
		description: "Added a new location: Ikeja Farm.",
	},
	{
		id: "00003",
		fullName: "Samuel Eze",
		date: "27/12/2024 - 09:45:10",
		module: "Farmer",
		actions: "edit",
		description: "Edited contact details for farmer John Doe.",
	},
	{
		id: "00004",
		fullName: "Fatima Danladi",
		date: "28/12/2024 - 11:05:45",
		module: "Location",
		actions: "delete",
		description: "Removed inactive location from database.",
	},
	{
		id: "00005",
		fullName: "David Akpan",
		date: "29/12/2024 - 14:22:33",
		module: "Farmer",
		actions: "create",
		description: "Added new farmer profile: Mary Johnson.",
	},
	{
		id: "00006",
		fullName: "Grace Okonkwo",
		date: "30/12/2024 - 16:50:12",
		module: "Location",
		actions: "update",
		description: "Updated GPS coordinates for Epe farmland.",
	},
	{
		id: "00007",
		fullName: "John Doe",
		date: "31/12/2024 - 12:40:55",
		module: "Farmer",
		actions: "delete",
		description: "Deleted farmer profile of Samuel Uche.",
	},
	{
		id: "00008",
		fullName: "Aisha Bello",
		date: "01/01/2025 - 08:30:20",
		module: "Location",
		actions: "create",
		description: "Added a new farming site: Ajah Greenhouse.",
	},
	{
		id: "00009",
		fullName: "Tunde Adeyemi",
		date: "02/01/2025 - 13:55:42",
		module: "Farmer",
		actions: "edit",
		description: "Updated farming equipment details for Green Harvest Group.",
	},
	{
		id: "00010",
		fullName: "Mary Johnson",
		date: "03/01/2025 - 17:20:05",
		module: "Location",
		actions: "update",
		description: "Updated irrigation details for Badagry farm.",
	},
];

export const deviceData: Device[] = [
	{
		id: "00001",
		serialNumber: "999005927WER",
		deviceAlias: "OneAcreDevice 001",
		dateJoined: "25/12/2024",
		status: "posted",
	},
	{
		id: "00002",
		serialNumber: "999005928XTR",
		deviceAlias: "OneAcreDevice 002",
		dateJoined: "12/11/2024",
		status: "not posted",
	},
	{
		id: "00003",
		serialNumber: "999005929YUI",
		deviceAlias: "OneAcreDevice 003",
		dateJoined: "05/10/2024",
		status: "posted",
	},
	{
		id: "00004",
		serialNumber: "999005930PLM",
		deviceAlias: "OneAcreDevice 004",
		dateJoined: "15/09/2024",
		status: "not posted",
	},
	{
		id: "00005",
		serialNumber: "999005931ZXC",
		deviceAlias: "OneAcreDevice 005",
		dateJoined: "30/08/2024",
		status: "posted",
	},
	{
		id: "00006",
		serialNumber: "999005932QWE",
		deviceAlias: "OneAcreDevice 006",
		dateJoined: "22/07/2024",
		status: "not posted",
	},
	{
		id: "00007",
		serialNumber: "999005933ASD",
		deviceAlias: "OneAcreDevice 007",
		dateJoined: "10/06/2024",
		status: "posted",
	},
	{
		id: "00008",
		serialNumber: "999005934ZVB",
		deviceAlias: "OneAcreDevice 008",
		dateJoined: "27/05/2024",
		status: "not posted",
	},
	{
		id: "00009",
		serialNumber: "999005935TYU",
		deviceAlias: "OneAcreDevice 009",
		dateJoined: "14/04/2024",
		status: "posted",
	},
	{
		id: "00010",
		serialNumber: "999005936IOP",
		deviceAlias: "OneAcreDevice 010",
		dateJoined: "02/03/2024",
		status: "not posted",
	},
];

export const postingData: Posting[] = [
	{
		id: "00001",
		serialNumber: "999005927WER",
		staffName: "Confidence Clinton",
		date: "25/12/2024",
		state: "Lagos",
		district: "Ikeja",
	},
	{
		id: "00002",
		serialNumber: "999005928XTR",
		staffName: "Ayomide Esther",
		date: "12/11/2024",
		state: "Ogun",
		district: "Abeokuta",
	},
	{
		id: "00003",
		serialNumber: "999005929YUI",
		staffName: "John Doe",
		date: "05/10/2024",
		state: "Kano",
		district: "Tarauni",
	},
	{
		id: "00004",
		serialNumber: "999005930PLM",
		staffName: "Jane Smith",
		date: "15/09/2024",
		state: "Rivers",
		district: "Port Harcourt",
	},
	{
		id: "00005",
		serialNumber: "999005931ZXC",
		staffName: "Emeka Okonkwo",
		date: "30/08/2024",
		state: "Anambra",
		district: "Awka",
	},
	{
		id: "00006",
		serialNumber: "999005932QWE",
		staffName: "Aisha Bello",
		date: "22/07/2024",
		state: "Kaduna",
		district: "Zaria",
	},
	{
		id: "00007",
		serialNumber: "999005933ASD",
		staffName: "David Johnson",
		date: "10/06/2024",
		state: "Oyo",
		district: "Ibadan",
	},
	{
		id: "00008",
		serialNumber: "999005934ZVB",
		staffName: "Fatima Musa",
		date: "27/05/2024",
		state: "Katsina",
		district: "Funtua",
	},
	{
		id: "00009",
		serialNumber: "999005935TYU",
		staffName: "Samuel Eze",
		date: "14/04/2024",
		state: "Enugu",
		district: "Nsukka",
	},
	{
		id: "00010",
		serialNumber: "999005936IOP",
		staffName: "Grace Adeyemi",
		date: "02/03/2024",
		state: "Ekiti",
		district: "Ado-Ekiti",
	},
];

export const groupData: Group[] = [
	{
		id: "00001",
		groupName: "Clinton Group",
		siteName: "Atunrase",
		pod: "Gbagada",
		district: "Ikeja",
		state: "Lagos",
	},
	{
		id: "00002",
		groupName: "Green Harvest",
		siteName: "Ajah Farms",
		pod: "Lekki",
		district: "Eti-Osa",
		state: "Lagos",
	},
	{
		id: "00003",
		groupName: "Agro Leaders",
		siteName: "Mainland Farms",
		pod: "Maryland",
		district: "Ikeja",
		state: "Lagos",
	},
	{
		id: "00004",
		groupName: "Farm Innovators",
		siteName: "Epe Agro",
		pod: "Ikorodu",
		district: "Epe",
		state: "Lagos",
	},
	{
		id: "00005",
		groupName: "Sustainable Crops",
		siteName: "Badagry Greens",
		pod: "Ojo",
		district: "Badagry",
		state: "Lagos",
	},
	{
		id: "00006",
		groupName: "Green Earth",
		siteName: "Surulere Hub",
		pod: "Lagos Island",
		district: "Surulere",
		state: "Lagos",
	},
	{
		id: "00007",
		groupName: "Harvest Kings",
		siteName: "Agege Produce",
		pod: "Iyana Ipaja",
		district: "Agege",
		state: "Lagos",
	},
	{
		id: "00008",
		groupName: "AgroTech",
		siteName: "Ikotun Estate",
		pod: "Alimosho",
		district: "Ikotun",
		state: "Lagos",
	},
	{
		id: "00009",
		groupName: "Organic Farmers",
		siteName: "Festac Agro",
		pod: "Amuwo Odofin",
		district: "Festac",
		state: "Lagos",
	},
	{
		id: "00010",
		groupName: "Golden Fields",
		siteName: "Mushin Agro Park",
		pod: "Oshodi",
		district: "Mushin",
		state: "Lagos",
	},
];
